dist: trusty
sudo: required

language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -y -qq update
  # - sudo apt-get -y install python-software-properties
  # - sudo apt-get -y install software-properties-common
  # - sudo add-apt-repository -y ppa:fkrull/deadsnakes-python2.7
  # - sudo apt-get -y -qq update
  - sudo apt-get install -y build-essential python2.7 python2.7-dev python-pip ipython
  - pip install setuptools
  - pip install jupyter
  - sudo apt-get install -y libfreetype6-dev libxft-dev libpng12-dev gfortran libatlas-base-dev liblapack-dev

install:
  - pip install --upgrade --no-deps -r MLslippage/requirements.txt
  - pip install -r MLslippage/requirements.txt
  - sudo apt-get install -y python-pygame

script:
  - sudo ./MLslippage/setup.sh 1

after script:
  - pip freeze
  - ./MLslippage/MLslippage/test.py
