dist: trusty
sudo: required

language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -y -pp update
  - sudo apt-get install -y --only-upgrade python-pip
  - sudo apt-get install -y ipython
  - sudo pip install setuptools
  - sudo pip install jupyter
  - sudo apt-get install -y libfreetype6-dev libxft-dev libpng12-dev
  - sudo apt-get install -y gfortran libatlas-base-dev liblapack-dev

install:
  - pip install --upgrade --no-deps -r MLslippage/requiremensts.txt
  - pip install -r MLslippage/requiremensts.txt

after_install:
  - sudo apt-get install -y python-pygame

script:
  - ./MLslippage/MLslippage/test.py

#before_script: true

#script: sudo ./MLslippage/setup.sh
